# Project Information
site_name: 漏洞知识库
site_description: 常见漏洞知识库, wiki, 漏洞wiki, 漏洞手册
site_author: 瓦都剋
site_url: https://vulwiki.readthedocs.io/zh_CN/latest/

# Repository
repo_name: '漏洞知识库'
repo_url: 'https://github.com/w2n1ck/vulwiki/'

# Copyright
copyright: 'Copyright &copy; 2019 瓦都剋'

# Contents
nav:
    - Home: 'index.md'
    - 1. Web安全漏洞:
        - '1.1 SQL注入': 'web/sql.md'
        - '1.2 cslf': 'web/csrf.md'
    - 2. 安卓客户端漏洞:
        - '2.1 XSS': 'web/xss.md'
        - '2.2 XSS': 'web/xss.md'

theme: readthedocs

# Theme
theme:
    name: 'readthedocs'
    language: 'zh'
    palette:
        primary: 'white'
        accent: 'red'
    logo:
        icon: 'school'
    feature:
        tabs: true
    font:
        text: 'Noto Sans'
        code: 'Source Code Pro'

# Customization
extra:
    search:
    copyright: 'CC BY-NC-SA 4.0'
